apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: abelnamesapce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: abelregistryy.azurecr.io/mydocker-repo:latest
        ports:
        - containerPort: 80
